abm_outputs:
  location: C:\test\visualizer_conversion
  tables:
    hh:
      filepath: output\householdData_3.csv
    per:
      filepath: output\personData_3.csv
    tours:
      filepath: output\indivTourData_3.csv
    trips:
      filepath: output\indivTripData_3.csv
    jtours:
      filepath: output\jointTourData_3.csv
    jtrips:
      filepath: output\jointTripData_3.csv
    wsLoc:
      filepath: output\wsLocResults_3.csv
    aoResults:
      filepath: output\aoResults.csv
    aoResults_Pre:
      filepath: output\aoResults_Pre.csv
    visitor_trips:
      filepath: output\visitorTrips.csv
    mazCorrespondence:
      filepath: visualizer\data\geographicXwalk_PMSA.csv

summaries:
  location: C:\test\pipeline
  summaries:
  - summary:
      type: count
      filepath: autoOwnership.csv
      table: aoResults
      fields: 'AO'
  - summary:
      type: count
      filepath: autoOwnership_Pre.csv
      table: aoResults_Pre
      fields: 'AO'